name: Minishell checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compilation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compilation
      run: make
    
    - name: Make re
      run: make re
    
    - name: Make clean
      run: make clean

    - name: Make fclean
      run: make fclean

  norminette:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette
        printf "\n$(PROJECT_NAME)[ Norm check : ]\n"
        norminette | grep -v "Notice: GLOBAL_VAR_DETECTED"

  builtins:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Launch builtins tester
      run: make builtins

  pipes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Launch pipes tester
      run: make pipes
  
  syntax:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Launch syntax tester
      run: make syntax

  var:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Launch var tester
      run: make var

  extras:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Launch extras tester
      run: make extras

  all:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Launch syntax tester
      run: make tester