name: Minishell checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compilation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compilation
      run: make
    
    - name: Make re
      run: make re
    
    - name: Make clean
      run: make clean

    - name: Make fclean
      run: make fclean

  norminette:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette
        norminette

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Premier tester
      run: make tester
