name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compilation
      run: make

    - name: Run tester
      run: make tester

    - name: Run Clean
      run: make fclean
