name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compilation
      run: make

    - name: Norminette
      run: make norminette

    - name: Run Premier tester
      run: make tester
    
    - name: Cleaning after first tester
      run: make fclean

    - name: Run Second tester
      run: make tester2
    
    - name: Cleaning after second tester
      run: make fclean

    - name: Re-make test
      run: make re

